### ISSUE TITLE
Error in GCM MAC

### ISSUE THREAD

**Issue by SidolFreiburg** [RUB-NDS/TLS-Attacker#37] opened 2018-02-12 16:09 UTC
Hello!

We are running the the TLS Attacker as a client. As cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 gets chosen. When we try to establish a connection to our Bouncy-Castle server, we get an bad_record_mac(20) alert as response to the Finished message. As far as we could debug it, the error seems to be caused by a deviating IV on the server and on the client side.

When we to the test with the same cipher suite with the TLS-Attacker as a server an Bouncy-Castle as a client everything works fine. Could that be caused by an error in our configuration?

Best regards
Matthias

**Comment by ic0ns** [comment] 2018-02-12 16:26
Hey Matthias,
which version of TLS-Attacker are you using? I just tried your setup with TLS-Attacker as a client and openssl as a server and the ciphersuite seemed to work. It may depend on the curve in the certificate you are using. I don't test ec certificates that much so there could also be a bug in TLS-Attacker. Can you try your test with TLS-Attacker 2.4 and if it still does not work provide me the debug output?

**Comment by ic0ns** [comment] 2018-02-12 16:43
Does it work with ECDHE_ECDSA and a CBC cipher?

**Comment by SidolFreiburg** [comment] 2018-02-12 17:15
We updated to Version 2.4 recently. Before the update, with version 2.3, the GCM mode worked. When we use the CBC mode, we get a different error. Attached to this post you will find logs. Furthermore, we have attached our configuration, which is performed in java. During our previous tests we did not configure the ECDSA public key (setDefaultClientEcPublicKey) explicitly. We have tried both ways, with and without explicitly configuring it. In the beginning of the log files, there is an error message, that the certificate could not be parsed. In the Version 2.3 of the attacker, this seemed to be okay.

[cbc_mode_log.txt](https://github.com/RUB-NDS/TLS-Attacker/files/1717123/cbc_mode_log.txt)
[gcm_mode_log.txt](https://github.com/RUB-NDS/TLS-Attacker/files/1717124/gcm_mode_log.txt)
[TestServerConversation.txt](https://github.com/RUB-NDS/TLS-Attacker/files/1717127/TestServerConversation.txt)

**Comment by ic0ns** [comment] 2018-02-13 08:56
Oh i see now. It seems to be that my last patch broke the encrypt then mac extension https://github.com/RUB-NDS/TLS-Attacker/tree/encryptThenMacfix - this should atleast help with the cbc mode problem.

**Comment by ic0ns** [comment] 2018-02-13 15:48
I checked your code and it seems to be that you are also using client authentication - which is not so well supported currently. The truncated Hmac extension you are adding could also be a problem (if the server would select it) since it is not fully implemented currently. 

I suggest that you try to reproduce the problem with mbedtls (which has nice debugging options) or openssl which allows you to check the error messages and compare master secrets

The certificate loading error in the beginning is stopping TLS-Attacker from auto loading your certificate. 
A problem could also be that you are using "import org.bouncycastle.asn1.x509.Certificate;" but TLS-Attacker usually operates on "org.bouncycastle.crypto.tls.Certificate;" - i am not sure if this makes a difference here or not. You can then use the CertificateUtils.java class to work with your certificate.

**Comment by SidolFreiburg** [comment] 2018-02-13 16:17
Thank you for your support!

I have switched to the "encryptThenMacfix" branch. When I disable the Extended-Master-Secret extension it works in CBC and GCM mode (haven't checked that on the master branch yet). It also works with the Client-Authentication enabled.

**Comment by ic0ns** [comment] 2018-02-13 16:27
ok now that you say it - it makes sense that with our current setup extended master secret does not work with client authentication since the keys are currently  always calculated after each client key exchange message and are not recalculated in the certificate verify message. I'll fix this in the next version

**Comment by ic0ns** [comment] 2018-09-26 10:11
Fixed in 2.6

**Closed by ic0ns** 2018-09-26 10:11 UTC
