### ISSUE TITLE
DHE 2048-bit ClientKeyExchange is sending 257 as Pubkey Length instead of 256

### ISSUE THREAD

**Issue by saravananmk** [RUB-NDS/TLS-Attacker#47] opened 2018-11-13 14:28 UTC
Server: Win2008R2 IIS setup to use 2048-bit DHE
Client: TLS-Attacker
cipher suite used: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f)

$ java -jar TLS-Client.jar -connect 10.11.12.1:443 -cipher TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
14:18:43 [main] INFO : DefaultWorkflowExecutor - Connecting to 10.11.12.1:443
14:18:43 [main] INFO : SendAction - Sending messages (client): CLIENT_HELLO,
14:18:44 [main] INFO : ReceiveAction - Received Messages (client):
14:18:44 [main] INFO : SendAction - Sending messages (client): DH_CLIENT_KEY_EXCHANGE, CHANGE_CIPHER_SPEC, FINISHED,
14:18:45 [main] INFO : ReceiveAction - Received Messages (client):

When I looked at the packet capture, noticed that after client sent CKE, CCS, FINISHED, the server is sending TCP RST.

$ tshark -nr ./tls-attacker-test.cap
    1   0.000000   10.11.51.1 → 10.11.12.1   TCP 74 40524 → 443 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1109457922 TSecr=0 WS=128
    2   0.000605   10.11.12.1 → 10.11.51.1   TCP 74 443 → 40524 [SYN, ACK] Seq=0 Ack=1 Win=8192 Len=0 MSS=1460 WS=256 SACK_PERM=1 TSval=11378711 TSecr=1109457922
    3   0.000633   10.11.51.1 → 10.11.12.1   TCP 66 40524 → 443 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=1109457923 TSecr=11378711
    4   0.087310   10.11.51.1 → 10.11.12.1   TLSv1.2 191 Client Hello
    5   0.093368   10.11.12.1 → 10.11.51.1   TCP 1514 [TCP segment of a reassembled PDU]
    6   0.093400   10.11.51.1 → 10.11.12.1   TCP 66 40524 → 443 [ACK] Seq=126 Ack=1449 Win=32128 Len=0 TSval=1109458015 TSecr=11378720
    7   0.093441   10.11.12.1 → 10.11.51.1   TLSv1.2 518 Server Hello, Certificate, Server Key Exchange, Server Hello Done
    8   0.093452   10.11.51.1 → 10.11.12.1   TCP 66 40524 → 443 [ACK] Seq=126 Ack=1901 Win=35072 Len=0 TSval=1109458015 TSecr=11378720
    9   1.091496   10.11.51.1 → 10.11.12.1   TLSv1.2 385 Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
   10   1.092379   10.11.12.1 → 10.11.51.1   TCP 60 443 → 40524 [RST, ACK] Seq=1901 Ack=445 Win=0 Len=0

Upon investigating the packet capture, I noticed that Client is sending 257 bytes as PubKey Length instead of 256 with a leading 0x00 in the pubkey.  May be it is failing because of that.

Handshake Protocol: Server Key Exchange
        Handshake Type: Server Key Exchange (12)
        Length: 1034
        Diffie-Hellman Server Params
            p Length: 256
            p: ffffffffffffffffadf85458a2bb4a9aafdc5620273d3cf1...
            g Length: 256
            g: 000000000000000000000000000000000000000000000000...
            Pubkey Length: 256
            Pubkey: 006590943c1433140dae48a7cbb4a16182c4d17717738c87...
            Signature Algorithm: rsa_pkcs1_sha1 (0x0201)
                Signature Hash Algorithm Hash: SHA1 (2)
                Signature Hash Algorithm Signature: RSA (1)
            Signature Length: 256
            Signature: 72923e13691ac70ea9102012f9eec224ccc10a5f377ac253...

TLSv1.2 Record Layer: Handshake Protocol: Client Key Exchange
    Content Type: Handshake (22)
    Version: TLS 1.2 (0x0303)
    Length: 263
    Handshake Protocol: Client Key Exchange
        Handshake Type: Client Key Exchange (16)
        Length: 259
        Diffie-Hellman Client Params
            Pubkey Length: 257
            Pubkey: 00b10b88e6e5a903d946bf6d7acedb6454a0a8fadd4db190...

In a 2048-bit DHE the pubkey size is 2048/8  = 256 bytes.  Then why ClientKeyExchange is sending 257 bytes (although the leading byte is 0x00)?   Is it a bug or I am missing something here?

**Comment by ic0ns** [comment] 2018-11-13 15:07
Hey saravananmk,
thanks for the report. You correctly found a "bug" in TLS-Attacker. Its already fixed in the development version. TLS-Attacker currently 2.6 sends DHE CKE with leading 0x00. This is technically not a bug since the specification does not prohibit doing this, however some servers do not like this and therefore abort the handshake. You can fix this bug by applying the following fix to the DHClientKeyExchangePreparator:
```
-        msg.setPublicKey(clientPublicKey.toByteArray());
+        msg.setPublicKey(ArrayConverter.bigIntegerToByteArray(clientPublicKey));
```

Thanks for reporting this!

**Closed** 2018-11-13 15:42 UTC
